server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**
        - id: CHANNEL-SERVICE
          uri: lb://CHANNEL-SERVICE
          predicates:
            - Path=/api/channel/**
        - id: INTERACTION-SERVICE
          uri: lb://INTERACTION-SERVICE
          predicates:
            - Path=/api/commit/**

      default-filters:
        - name: JwtFilter


  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:8080", "http://localhost:3000", "http://159.65.119.240:8080","http://localhost:3001"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://${EUREKA_HOST:localhost}:8761/eureka/}
  instance:
    preferIpAddress: true

springdoc:
  swagger-ui:
    path: /api/auth/swagger-ui
  api-docs:
    path: /api/auth/v3/api-docs




jwt:
  secret: qwefklsdfj3roif134adsj14fdslkjf1234fiodwq


